### ISSUE TITLE
Production-ready release

### ISSUE THREAD

**Issue by driimus** [driimus/dynamodb-data-mapper-js#4]
- [x] enable any skipped tests which are still required
- [x] driimus/dynamodb-data-mapper-js#3
- [ ] #13
- [ ] #14
- [x] driimus/dynamodb-data-mapper-js#5
- [x] driimus/dynamodb-data-mapper-js#6 
- [ ] #12
- [ ] driimus/dynamodb-data-mapper-js#1
- [ ] #71
